---
title: "Categorical Model Bayesian Checks"
format: 
  pptx:
    prefer-html: true
execute:
  warning: false
  message: false
  cache: true
---

```{r setup}
library(zoib)
library(tidyverse)
library(GGally)
library(ggpubr)
library(kableExtra)
library(mice)
library(parallel)

theme_set(theme_pubr(legend = "bottom"))
```

# read imputed data
```{r readin}
dat<- readRDS("../nnns_attention_2cat.rds")
```

# Run Zoib Model

```{r preop}
#| eval: false
set.seed(11282023)

tictoc::tic()

# Define a function for model fitting
fit_model <- function(d) {
  zoib(
    Percent_of_feeds_taken_by_mouth_at_discharge ~
      Pre_op_attention_2cat +
      Length_of_intubation_days +
      Cardiac_Anatomy +
      Age_at_Surgery_days +
      Female #x1 design matrix
    | 1 | #x2 design matrix
      Pre_op_attention_2cat +
      Length_of_intubation_days +
      Cardiac_Anatomy +
      Age_at_Surgery_days +
      Female | #X3 design matrix
      Pre_op_attention_2cat +
      Length_of_intubation_days +
      Cardiac_Anatomy +
      Age_at_Surgery_days +
      Female, #x4 design matrix
    data = d,
    n.response = 1,
    zero.inflation = TRUE,
    one.inflation = TRUE,
    link.mu = "logit",
    link.x0 = "logit",
    link.x1 = "logit",
    random = 0,
    n.chain = 4,
    n.iter = 3000,
    n.thin = 2,
    n.burn = 200,
    seeds = c(11, 29, 20, 23)
  )
}
pre_model_results <- fit_model(dat)
# Save results
saveRDS(pre_model_results, "cat_pre_op_model.rds")

tictoc::toc()
```


```{r postop}
#| eval: false
set.seed(11282023)

tictoc::tic()

# Define a function for model fitting
fit_model <- function(d) {
  zoib(
    Percent_of_feeds_taken_by_mouth_at_discharge ~
      Post_op_attention_2cat +
      Length_of_intubation_days +
      Cardiac_Anatomy +
      Age_at_Surgery_days +
      Female #x1 design matrix
    | 1 | #x2 design matrix
      Post_op_attention_2cat +
      Length_of_intubation_days +
      Cardiac_Anatomy +
      Age_at_Surgery_days +
      Female | #X3 design matrix
      Post_op_attention_2cat +
      Length_of_intubation_days +
      Cardiac_Anatomy +
      Age_at_Surgery_days +
      Female, #x4 design matrix
    data = d,
    n.response = 1,
    zero.inflation = TRUE,
    one.inflation = TRUE,
    link.mu = "logit",
    link.x0 = "logit",
    link.x1 = "logit",
    random = 0,
    n.chain = 4,
    n.iter = 3000,
    n.thin = 2,
    n.burn = 200,
    seeds = c(11, 29, 20, 23)
  )
}

# Parallelize model fitting
post_model_results <- dat |> fit_model()

# Save results
saveRDS(post_model_results, "cat_post_op_model.rds")

tictoc::toc()
```

# Load results
```{r}
post_model_results = readRDS("cat_post_op_model.rds")
pre_model_results = readRDS("cat_pre_op_model.rds")
```

# Convergence Plots

## Traceplots

### Pre-op
```{r}
pre_model_results$coeff |> traceplot()
```

### Post-op
```{r}
post_model_results$coeff |> traceplot()
```

## Autocorrelation plots

### Pre-op
```{r}
pre_model_results$coeff |> autocorr.plot()
```
### Post-op
```{r}
post_model_results$coeff |> autocorr.plot()
```


# Summary table
```{r}
summary_pre_op = pre_model_results$coeff |> summary()
summary_post_op = post_model_results$coeff |> summary()

rnames = c("Baseline","Attention Score","Length of Intubation (d)",
           "Single Ventricle w/ Arch Obstruction","Two Ventricles w/ Arch Obstruction",
           "Age", "Female")

pre_mean = summary_pre_op$statistics[,"Mean"]
pre_lb = summary_pre_op$quantiles[,"2.5%"] 
pre_ub = summary_pre_op$quantiles[,"97.5%"]



post_mean = summary_post_op$statistics[,"Mean"]
post_lb   = summary_post_op$quantiles[,"2.5%"] 
post_ub   = summary_post_op$quantiles[,"97.5%"] 


pre_b_df= cbind("Mean"= pre_mean[1:7] |> exp() |> round(2),
                 "2.5%"= pre_lb[1:7] |> exp() |> round(2),
                 "97.5%" = pre_ub[1:7] |> exp() |> round(2))

pre_b0_df= cbind("Mean"= pre_mean[8:14] |> exp() |> round(2),
               "2.5%"= pre_lb[8:14] |> exp() |> round(2),
               "97.5%" = pre_ub[8:14] |> exp() |> round(2))
pre_b1_df= cbind("Mean"= pre_mean[15:21] |> exp() |> round(2),
               "2.5%"= pre_lb[15:21] |> exp() |> round(2),
               "97.5%" = pre_ub[15:21] |> exp() |> round(2))

pre_df = cbind(pre_b_df,pre_b0_df,pre_b1_df)
rownames(pre_df) = rnames



post_b_df= cbind("Mean"= post_mean[1:7] |> exp() |> round(2),
                 "2.5%"= post_lb[1:7] |> exp() |> round(2),
                 "97.5%" = post_ub[1:7] |> exp() |> round(2))

post_b0_df= cbind("Mean"= post_mean[8:14] |> exp() |> round(2),
               "2.5%"= post_lb[8:14] |> exp() |> round(2),
               "97.5%" = post_ub[8:14] |> exp() |> round(2))
post_b1_df= cbind("Mean "= post_mean[15:21] |> exp() |> round(2),
               "2.5%"= post_lb[15:21] |> exp() |> round(2),
               "97.5%" = post_ub[15:21] |> exp() |> round(2))

post_df = cbind(post_b_df,post_b0_df,post_b1_df)
rownames(post_df) = rnames


pre_kable = pre_df |>
  kable(caption = "Odds Ratio of Percent Oral Feed Model Results (Pre-Operation)") |>
  add_header_above(header = c("Predictor" = 1,
                            "Odds of Oral Feed \n when oral feed between 0 and 1" = 3,
                              "Odds of 0% Oral Feed" = 3,
                              "Odds of 100% Oral Feed" =3)) |>
  add_footnote(paste("Posterior variance is estimated to be ", pre_mean[22] |> exp() |> round(2),
                     " (",pre_lb[22] |> exp() |> round(2),",", pre_ub[22]|> exp()|> round(2),")"))

post_kable = post_df |>
  kable(caption = "Odds Ratio of Percent Oral Feed Model Results (Post-Operation)") |>
  add_header_above(header = c("Predictor" = 1,
                            "Odds of Oral Feed \n when oral feed between 0 and 1" = 3,
                              "Odds of 0% Oral Feed" = 3,
                              "Odds of 100% Oral Feed" =3)) |>
  add_footnote(paste("Posterior variance is estimated to be ", post_mean[22] |> exp() |> round(2),
                     " (",post_lb[22] |> exp() |> round(2),",", post_ub[22]|> exp()|> round(2),")"))
```

## Pre-operation
```{r}
pre_kable
```

## Post-operation
```{r}
post_kable
```



## Posterior Predictive Check

## Pre Op
```{r}
pre_op_pred = pre_model_results$ypred |> runjags::combine.mcmc()

set.seed(1262023)
pre_sample_pred =sample_n(pre_op_pred|> as.data.frame(),9)

par(mfrow=c(3,3))
for(i in 1:9) pre_sample_pred[i,] |> as.numeric() |>hist(main = "",
                            xlab = "")

mtext("preerior Predictive Samples, pre-op Model", side = 3, line = -2, outer = TRUE)

par(mfrow = c(1,1))
dat$Percent_of_feeds_taken_by_mouth_at_discharge |>
  hist(main = "Histogram of Percent Oral Feeds",xlab = "Percent Oral Feeds")
```

## Post Op
```{r}
post_op_pred = post_model_results$ypred |> runjags::combine.mcmc()

set.seed(1262023)
post_sample_pred =sample_n(post_op_pred|> as.data.frame(),9)

par(mfrow=c(3,3))
for(i in 1:9) post_sample_pred[i,] |> as.numeric() |>hist(main = "",
                            xlab = "")

mtext("Posterior Predictive Samples, Post-op Model", side = 3, line = -2, outer = TRUE)

par(mfrow = c(1,1))
dat$Percent_of_feeds_taken_by_mouth_at_discharge |>
  hist(main = "Histogram of Percent Oral Feeds",xlab = "Percent Oral Feeds")
```

```{r}
#| eval: false
pre_q25 = rep(NA, 1000)
pre_q975 = rep(NA, 1000)
post_q25 = rep(NA, 1000)
post_q975 = rep(NA,1000)
for(i in 1:1000){
  m = pre_sample_pred[i,]|> as.numeric()
  pre_q25[i] = quantile(m, .025)
  pre_q975[i] = quantile(m, .975)
  
  m = post_sample_pred[i,] |> as.numeric()
  post_q25[i] = quantile(m, .025)
  post_q975[i] = quantile(m, .975)
}

q25 = dat$Percent_of_feeds_taken_by_mouth_at_discharge |>
  quantile(.025)
q975 = dat$Percent_of_feeds_taken_by_mouth_at_discharge |>
  quantile(.975)

post_q25 |> hist(main = "Histogram of 2.5th Percentile of Regenerated Samples \n Post-op Model")
abline(v = q25, col = "blue")

pre_q25 |> hist(main = "Histogram of 2.5th Percentile of Regenerated Samples \n Pre-op Model")
abline(v = q25, col = "blue")

post_q975 |> hist(main = "Histogram of 97.5th Percentile of Regenerated Samples \n Post-op Model")
abline(v = q975, col = "blue")

pre_q975 |> hist(main = "Histogram of 97.5th Percentile of Regenerated Samples \n Pre-op Model")
abline(v = q975, col = "blue")

d = dat$Percent_of_feeds_taken_by_mouth_at_discharge


d_no01 = d[d !=0 & d != 1]
d_no01 |> hist(main = "Histogram of Percentage Oral Feed \n excluding 0 and 1")


post_q25[d !=0 & d != 1] |> hist(main = "Histogram of 2.5th Percentile of Regenerated Samples \n Post-op Model")
abline(v = quantile(d_no01,.025), col = "blue")

pre_q25[d !=0 & d != 1] |> hist(main = "Histogram of 2.5th Percentile of Regenerated Samples \n Pre-op Model")
abline(v = quantile(d_no01,.025), col = "blue")

post_q975[d !=0 & d != 1] |> hist(main = "Histogram of 97.5th Percentile of Regenerated Samples \n Post-op Model")
abline(v = quantile(d_no01,.975), col = "blue")

pre_q975[d !=0 & d != 1] |> hist(main = "Histogram of 97.5th Percentile of Regenerated Samples \n Pre-op Model")
abline(v = quantile(d_no01,.975), col = "blue")

d = dat$Percent_of_feeds_taken_by_mouth_at_discharge
```

