---
title: "Beta Regression"
format:
  html:
    embed-resources: true
    self-contained-math: true
    code-fold: true
    code-summary: "Show the code"
    toc: true
    toc-depth: 6
    toc-location: left
execute:
  warning: false
  message: false
---

```{r setup}
library(zoib)
library(tidyverse)
library(GGally)
library(ggpubr)
library(kableExtra)
library(mice)

theme_set(theme_pubr(legend = "bottom"))


nnns_imputed<- readRDS("../Haojia_work/nnns_imputed.rds")


```

# read imputed data
```{r readin}

dat=complete(nnns_imputed,1)
attach(dat);Percent_of_feeds_taken_by_mouth_at_discharge

```



# Use ZOIB package

## ZOIB Model

$$
f(y_i|\eta_i) = \begin{cases}
p_i, & y_i =0 \\
(1-p_i)q_i, & y_i =1 \\
(1 − p_i)(1 − q_i)Beta(\alpha_{i_1}, \alpha_{i_2}) &y_i \in (0, 1)
\end{cases}
$$

$$
\begin{aligned}
logit\left(\mu^{(0,1)} = \frac{\alpha_1}{\alpha_1+ \alpha_2}\right) = \mathbf x_1 \boldsymbol \beta_1 + I_1(\mathbf z_{1,i}\gamma_{1,i}) \\
log\left(v_i = \alpha_1+ \alpha_2\right) = \mathbf x_2 \boldsymbol \beta_2 + I_2(\mathbf z_{2,i}\gamma_{2,i}) \\
logit\left(p_i\right) = \mathbf x_3 \boldsymbol \beta_3 + I_1(\mathbf z_{3,i}\gamma_{3,i}) \\
logit\left(q_i\right) = \mathbf x_4 \boldsymbol \beta_4 + I_1(\mathbf z_{4,i}\gamma_{4 ,i})
\end{aligned}
$$

## Fit ZOIB model
```{r zoib}
#| eval: false
set.seed(11282023) #Set seed, bayesian model!

tictoc::tic()
pre_op_model =zoib(Percent_of_feeds_taken_by_mouth_at_discharge #Response
            ~Pre_Op_NNNS_attention_score+
              Length_of_intubation_days+
              #Genetic_Syndrome_or_Chromosomal_Abnormality+
              Cardiac_Anatomy+
              Age_at_Surgery_days+
              Female
              #x1 design matrix
       | 1 #x2 design matrix- estimating variance
     |Pre_Op_NNNS_attention_score+
              Length_of_intubation_days+
              #Genetic_Syndrome_or_Chromosomal_Abnormality+
              Cardiac_Anatomy+
              Age_at_Surgery_days+
              Female #x3 design matrix
     |Pre_Op_NNNS_attention_score+
              Length_of_intubation_days+
              #Genetic_Syndrome_or_Chromosomal_Abnormality+
              Cardiac_Anatomy+
              Age_at_Surgery_days+
              Female, #x4 design matrix
     data = dat,
     n.response = 1,
     zero.inflation = TRUE,
     one.inflation = TRUE,
     link.mu = "logit",
     link.x0 = "logit",
     link.x1 =  "logit",
     random = 0,
     n.chain = 4, # number of MCMC chains
     n.iter = 3000, #number of iterations before burn/thin
     n.thin = 2, # thinning period
     n.burn = 200, # burn-in period 
     seeds = c(11,29,20,23) #vector of seeds for chains to make reproducable
     )
tictoc::toc()
saveRDS(pre_op_model, file="model1.RData")
```


## Interpreting output:

b: vector of estimates from Eqn 1; that is, g(mu) = xb\*b +z\*gamma

d: vector of estimates from Eqn 2; that is, log(eta) = xd\*d+z\*gamma

b0: vector of estimates from Eqn 3; that is, g(p0) = x0\*b0 +z\*gamma

b1: vector of estimates from Eqn ;4 that is, g(p1) = x1\*b1+z\*gamma

```{r model1results}
model1 =readRDS(file="model1.RData")

model1$coeff |> summary()
```

## Check convergence

### Traceplots
```{r convergence}
traceplot(model1$coeff)
```

### Autocorrelation plots
```{r}
autocorr.plot(model1$coeff)
```

